default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  username: <%= ENV.fetch('POSTGRES_USER', 'prensai_api') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'prensai_api') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  database: prensai_api_development

test:
  <<: *default
  database: prensai_api_test<%= ENV['TEST_ENV_NUMBER'] %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
production:
  <<: *default
