local:
  service: DiskWithHost
  root: <%= Rails.root.join('storage') %>

test:
  service: DiskWithHost
  root: <%= Rails.root.join('tmp/storage') %>

# Google Cloud Storage configuration for production
google:
  service: GCS
  project: <%= ENV['GCS_PROJECT_ID'] %>
  credentials: <%= ENV['GCS_CREDENTIALS_JSON'] %>
  bucket: <%= ENV['GCS_BUCKET_NAME'] %>
